server:
  port: 8770

spring:
  application:
    name: blog-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: cnblogs-client
          uri: lb://CNBLOGS-CLIENT
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - RequestTime=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/